#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace student_health_records_system
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Student_Health_Record_System")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::student_health_records_system.Properties.Settings.Default.Student_Health_Record_SystemConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<vwAdminIDandName> vwAdminIDandNames
		{
			get
			{
				return this.GetTable<vwAdminIDandName>();
			}
		}
		
		public System.Data.Linq.Table<vwStudentsIDAndName> vwStudentsIDAndNames
		{
			get
			{
				return this.GetTable<vwStudentsIDAndName>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspRetrieveStudentFiles")]
		public ISingleResult<uspRetrieveStudentFilesResult> uspRetrieveStudentFiles([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(9)")] string studentID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), studentID);
			return ((ISingleResult<uspRetrieveStudentFilesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspRetrieveStudentRecords")]
		public ISingleResult<uspRetrieveStudentRecordsResult> uspRetrieveStudentRecords([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(9)")] string studentID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), studentID);
			return ((ISingleResult<uspRetrieveStudentRecordsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspGetAdminUsernames")]
		public ISingleResult<uspGetAdminUsernamesResult> uspGetAdminUsernames()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<uspGetAdminUsernamesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspGetAdminIDs")]
		public ISingleResult<uspGetAdminIDsResult> uspGetAdminIDs()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<uspGetAdminIDsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspRegisterAdmin")]
		public int uspRegisterAdmin([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(5)")] string adminID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string adminFName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string adminMName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string adminLName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string adminUName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string adminPWord, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string adminPhoneNum, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string adminEmail, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(2)")] string adminDept, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(3)")] string adminAccess, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> dateCreated, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> dateModified)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), adminID, adminFName, adminMName, adminLName, adminUName, adminPWord, adminPhoneNum, adminEmail, adminDept, adminAccess, dateCreated, dateModified);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspGetAdminCredentials")]
		public ISingleResult<uspGetAdminCredentialsResult> uspGetAdminCredentials([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string adminUsername)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), adminUsername);
			return ((ISingleResult<uspGetAdminCredentialsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspUpdateAccountStatusLogIn")]
		public int uspUpdateAccountStatusLogIn([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string adminUsername)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), adminUsername);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspUpdateAccountStatusLogOut")]
		public int uspUpdateAccountStatusLogOut([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string adminUsername)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), adminUsername);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspDeleteAccount")]
		public int uspDeleteAccount([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(5)")] string adminID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), adminID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspGetAdminUsernameByAdminID")]
		public ISingleResult<uspGetAdminUsernameByAdminIDResult> uspGetAdminUsernameByAdminID([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(5)")] string adminID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), adminID);
			return ((ISingleResult<uspGetAdminUsernameByAdminIDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspUpdateAdmin")]
		public int uspUpdateAdmin([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(5)")] string adminID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string adminFName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string adminMName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string adminLName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string adminUName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string adminPWord, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string adminPhoneNum, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string adminEmail, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(2)")] string adminDept, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(3)")] string adminAccess, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(3)")] string adminStatus, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> dateModified)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), adminID, adminFName, adminMName, adminLName, adminUName, adminPWord, adminPhoneNum, adminEmail, adminDept, adminAccess, adminStatus, dateModified);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspGetAdminInfoByID")]
		public ISingleResult<uspGetAdminInfoByIDResult> uspGetAdminInfoByID([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(5)")] string adminID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), adminID);
			return ((ISingleResult<uspGetAdminInfoByIDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspCheckAdminUsernameExistence")]
		public ISingleResult<uspCheckAdminUsernameExistenceResult> uspCheckAdminUsernameExistence([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(5)")] string adminID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string adminUsername)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), adminID, adminUsername);
			return ((ISingleResult<uspCheckAdminUsernameExistenceResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspDeleteAdminAccount")]
		public int uspDeleteAdminAccount([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(5)")] string adminID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), adminID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspGetAllStudentIDs")]
		public ISingleResult<uspGetAllStudentIDsResult> uspGetAllStudentIDs()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<uspGetAllStudentIDsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspGetAdminNameAndID")]
		public ISingleResult<uspGetAdminNameAndIDResult> uspGetAdminNameAndID()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<uspGetAdminNameAndIDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspAddStudent")]
		public int uspAddStudent([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(9)")] string studentID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string studentFName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string studentMName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string studentLName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1)")] string studentGender, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> studentBirthdate, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string studentAge, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string studentPNum, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string studentEmail, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> dateCreated, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> dateModified)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), studentID, studentFName, studentMName, studentLName, studentGender, studentBirthdate, studentAge, studentPNum, studentEmail, dateCreated, dateModified);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspGetStudentCount")]
		public ISingleResult<uspGetStudentCountResult> uspGetStudentCount()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<uspGetStudentCountResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getAllFileCountOfStudentByID")]
		public ISingleResult<getAllFileCountOfStudentByIDResult> getAllFileCountOfStudentByID([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(9)")] string studentID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), studentID);
			return ((ISingleResult<getAllFileCountOfStudentByIDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspAddStudentFiles")]
		public int uspAddStudentFiles([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(9)")] string studentID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(11)")] string stuFileID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string stuFileName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string stuFileType, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string stuFileLocation, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> dateCreated, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> dateModified)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), studentID, stuFileID, stuFileName, stuFileType, stuFileLocation, dateCreated, dateModified);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspGetAllStudentNamesAndID")]
		public ISingleResult<uspGetAllStudentNamesAndIDResult> uspGetAllStudentNamesAndID()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<uspGetAllStudentNamesAndIDResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vwAdminIDandName")]
	public partial class vwAdminIDandName
	{
		
		private string _Admin_ID;
		
		private string _Admin_Name;
		
		private string _Admin_Username;
		
		public vwAdminIDandName()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Admin ID]", Storage="_Admin_ID", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string Admin_ID
		{
			get
			{
				return this._Admin_ID;
			}
			set
			{
				if ((this._Admin_ID != value))
				{
					this._Admin_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Admin Name]", Storage="_Admin_Name", DbType="VarChar(302) NOT NULL", CanBeNull=false)]
		public string Admin_Name
		{
			get
			{
				return this._Admin_Name;
			}
			set
			{
				if ((this._Admin_Name != value))
				{
					this._Admin_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Admin Username]", Storage="_Admin_Username", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Admin_Username
		{
			get
			{
				return this._Admin_Username;
			}
			set
			{
				if ((this._Admin_Username != value))
				{
					this._Admin_Username = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vwStudentsIDAndNames")]
	public partial class vwStudentsIDAndName
	{
		
		private string _Student_ID;
		
		private string _Student_Name;
		
		public vwStudentsIDAndName()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Student ID]", Storage="_Student_ID", DbType="VarChar(9) NOT NULL", CanBeNull=false)]
		public string Student_ID
		{
			get
			{
				return this._Student_ID;
			}
			set
			{
				if ((this._Student_ID != value))
				{
					this._Student_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Student Name]", Storage="_Student_Name", DbType="VarChar(303) NOT NULL", CanBeNull=false)]
		public string Student_Name
		{
			get
			{
				return this._Student_Name;
			}
			set
			{
				if ((this._Student_Name != value))
				{
					this._Student_Name = value;
				}
			}
		}
	}
	
	public partial class uspRetrieveStudentFilesResult
	{
		
		private string _fileID;
		
		private string _fileName;
		
		private string _fileType;
		
		private string _fileRecordType;
		
		private string _fileLocation;
		
		public uspRetrieveStudentFilesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fileID", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string fileID
		{
			get
			{
				return this._fileID;
			}
			set
			{
				if ((this._fileID != value))
				{
					this._fileID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fileName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string fileName
		{
			get
			{
				return this._fileName;
			}
			set
			{
				if ((this._fileName != value))
				{
					this._fileName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fileType", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string fileType
		{
			get
			{
				return this._fileType;
			}
			set
			{
				if ((this._fileType != value))
				{
					this._fileType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fileRecordType", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string fileRecordType
		{
			get
			{
				return this._fileRecordType;
			}
			set
			{
				if ((this._fileRecordType != value))
				{
					this._fileRecordType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fileLocation", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string fileLocation
		{
			get
			{
				return this._fileLocation;
			}
			set
			{
				if ((this._fileLocation != value))
				{
					this._fileLocation = value;
				}
			}
		}
	}
	
	public partial class uspRetrieveStudentRecordsResult
	{
		
		private string _studentID;
		
		private string _studentFName;
		
		private string _studentMName;
		
		private string _studentLName;
		
		private string _studentEmail;
		
		private string _studentPhoneNum;
		
		public uspRetrieveStudentRecordsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studentID", DbType="VarChar(9) NOT NULL", CanBeNull=false)]
		public string studentID
		{
			get
			{
				return this._studentID;
			}
			set
			{
				if ((this._studentID != value))
				{
					this._studentID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studentFName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string studentFName
		{
			get
			{
				return this._studentFName;
			}
			set
			{
				if ((this._studentFName != value))
				{
					this._studentFName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studentMName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string studentMName
		{
			get
			{
				return this._studentMName;
			}
			set
			{
				if ((this._studentMName != value))
				{
					this._studentMName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studentLName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string studentLName
		{
			get
			{
				return this._studentLName;
			}
			set
			{
				if ((this._studentLName != value))
				{
					this._studentLName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studentEmail", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string studentEmail
		{
			get
			{
				return this._studentEmail;
			}
			set
			{
				if ((this._studentEmail != value))
				{
					this._studentEmail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studentPhoneNum", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string studentPhoneNum
		{
			get
			{
				return this._studentPhoneNum;
			}
			set
			{
				if ((this._studentPhoneNum != value))
				{
					this._studentPhoneNum = value;
				}
			}
		}
	}
	
	public partial class uspGetAdminUsernamesResult
	{
		
		private string _adminUsername;
		
		public uspGetAdminUsernamesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adminUsername", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string adminUsername
		{
			get
			{
				return this._adminUsername;
			}
			set
			{
				if ((this._adminUsername != value))
				{
					this._adminUsername = value;
				}
			}
		}
	}
	
	public partial class uspGetAdminIDsResult
	{
		
		private string _admin_ID;
		
		public uspGetAdminIDsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_admin_ID", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string admin_ID
		{
			get
			{
				return this._admin_ID;
			}
			set
			{
				if ((this._admin_ID != value))
				{
					this._admin_ID = value;
				}
			}
		}
	}
	
	public partial class uspGetAdminCredentialsResult
	{
		
		private string _adminUsername;
		
		private string _adminPassword;
		
		private string _adminAccess;
		
		private string _adminStatus;
		
		public uspGetAdminCredentialsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adminUsername", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string adminUsername
		{
			get
			{
				return this._adminUsername;
			}
			set
			{
				if ((this._adminUsername != value))
				{
					this._adminUsername = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adminPassword", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string adminPassword
		{
			get
			{
				return this._adminPassword;
			}
			set
			{
				if ((this._adminPassword != value))
				{
					this._adminPassword = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adminAccess", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string adminAccess
		{
			get
			{
				return this._adminAccess;
			}
			set
			{
				if ((this._adminAccess != value))
				{
					this._adminAccess = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adminStatus", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string adminStatus
		{
			get
			{
				return this._adminStatus;
			}
			set
			{
				if ((this._adminStatus != value))
				{
					this._adminStatus = value;
				}
			}
		}
	}
	
	public partial class uspGetAdminUsernameByAdminIDResult
	{
		
		private string _admin_userName;
		
		public uspGetAdminUsernameByAdminIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_admin_userName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string admin_userName
		{
			get
			{
				return this._admin_userName;
			}
			set
			{
				if ((this._admin_userName != value))
				{
					this._admin_userName = value;
				}
			}
		}
	}
	
	public partial class uspGetAdminInfoByIDResult
	{
		
		private string _admin_ID;
		
		private string _admin_firstName;
		
		private string _admin_middleName;
		
		private string _admin_lastName;
		
		private string _admin_userName;
		
		private string _admin_password;
		
		private string _admin_phoneNum;
		
		private string _admin_email;
		
		private string _admin_department;
		
		private string _admin_access;
		
		private string _admin_status;
		
		private System.DateTime _date_created;
		
		private System.DateTime _date_modified;
		
		public uspGetAdminInfoByIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_admin_ID", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string admin_ID
		{
			get
			{
				return this._admin_ID;
			}
			set
			{
				if ((this._admin_ID != value))
				{
					this._admin_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_admin_firstName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string admin_firstName
		{
			get
			{
				return this._admin_firstName;
			}
			set
			{
				if ((this._admin_firstName != value))
				{
					this._admin_firstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_admin_middleName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string admin_middleName
		{
			get
			{
				return this._admin_middleName;
			}
			set
			{
				if ((this._admin_middleName != value))
				{
					this._admin_middleName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_admin_lastName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string admin_lastName
		{
			get
			{
				return this._admin_lastName;
			}
			set
			{
				if ((this._admin_lastName != value))
				{
					this._admin_lastName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_admin_userName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string admin_userName
		{
			get
			{
				return this._admin_userName;
			}
			set
			{
				if ((this._admin_userName != value))
				{
					this._admin_userName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_admin_password", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string admin_password
		{
			get
			{
				return this._admin_password;
			}
			set
			{
				if ((this._admin_password != value))
				{
					this._admin_password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_admin_phoneNum", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string admin_phoneNum
		{
			get
			{
				return this._admin_phoneNum;
			}
			set
			{
				if ((this._admin_phoneNum != value))
				{
					this._admin_phoneNum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_admin_email", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string admin_email
		{
			get
			{
				return this._admin_email;
			}
			set
			{
				if ((this._admin_email != value))
				{
					this._admin_email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_admin_department", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string admin_department
		{
			get
			{
				return this._admin_department;
			}
			set
			{
				if ((this._admin_department != value))
				{
					this._admin_department = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_admin_access", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string admin_access
		{
			get
			{
				return this._admin_access;
			}
			set
			{
				if ((this._admin_access != value))
				{
					this._admin_access = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_admin_status", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string admin_status
		{
			get
			{
				return this._admin_status;
			}
			set
			{
				if ((this._admin_status != value))
				{
					this._admin_status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_created", DbType="DateTime NOT NULL")]
		public System.DateTime date_created
		{
			get
			{
				return this._date_created;
			}
			set
			{
				if ((this._date_created != value))
				{
					this._date_created = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_modified", DbType="DateTime NOT NULL")]
		public System.DateTime date_modified
		{
			get
			{
				return this._date_modified;
			}
			set
			{
				if ((this._date_modified != value))
				{
					this._date_modified = value;
				}
			}
		}
	}
	
	public partial class uspCheckAdminUsernameExistenceResult
	{
		
		private string _admin_ID;
		
		public uspCheckAdminUsernameExistenceResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_admin_ID", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string admin_ID
		{
			get
			{
				return this._admin_ID;
			}
			set
			{
				if ((this._admin_ID != value))
				{
					this._admin_ID = value;
				}
			}
		}
	}
	
	public partial class uspGetAllStudentIDsResult
	{
		
		private string _student_ID;
		
		public uspGetAllStudentIDsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_student_ID", DbType="VarChar(9) NOT NULL", CanBeNull=false)]
		public string student_ID
		{
			get
			{
				return this._student_ID;
			}
			set
			{
				if ((this._student_ID != value))
				{
					this._student_ID = value;
				}
			}
		}
	}
	
	public partial class uspGetAdminNameAndIDResult
	{
		
		private string _adminUsername;
		
		private string _adminID;
		
		public uspGetAdminNameAndIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adminUsername", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string adminUsername
		{
			get
			{
				return this._adminUsername;
			}
			set
			{
				if ((this._adminUsername != value))
				{
					this._adminUsername = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adminID", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string adminID
		{
			get
			{
				return this._adminID;
			}
			set
			{
				if ((this._adminID != value))
				{
					this._adminID = value;
				}
			}
		}
	}
	
	public partial class uspGetStudentCountResult
	{
		
		private System.Nullable<int> _Column1;
		
		public uspGetStudentCountResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="Int")]
		public System.Nullable<int> Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
	}
	
	public partial class getAllFileCountOfStudentByIDResult
	{
		
		private System.Nullable<int> _Column1;
		
		public getAllFileCountOfStudentByIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="Int")]
		public System.Nullable<int> Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
	}
	
	public partial class uspGetAllStudentNamesAndIDResult
	{
		
		private string _Student_ID;
		
		private string _Student_Name;
		
		public uspGetAllStudentNamesAndIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Student ID]", Storage="_Student_ID", DbType="VarChar(9) NOT NULL", CanBeNull=false)]
		public string Student_ID
		{
			get
			{
				return this._Student_ID;
			}
			set
			{
				if ((this._Student_ID != value))
				{
					this._Student_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Student Name]", Storage="_Student_Name", DbType="VarChar(303) NOT NULL", CanBeNull=false)]
		public string Student_Name
		{
			get
			{
				return this._Student_Name;
			}
			set
			{
				if ((this._Student_Name != value))
				{
					this._Student_Name = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
